In [1]:
import numpy as np
from qiskit import *
class ClassicalOperator:
        
        def __init__(self):
            self.shangGua = np.array([[-1],[-1],[-1]])
            self.shiaGua = np.array([[-1],[-1],[-1]])
        '''
        變卦
        '''
        def bianGua(self): #shangGua: 上卦 shiaGua:下卦
            assert self.shangGua[0,0] != -1
            print("[classical變卦]")
            shangGua = np.where((self.shangGua==0)|(self.shangGua==1), self.shangGua^1, self.shangGua)
            shiaGua = np.where((self.shiaGua==0)|(self.shiaGua==1), self.shiaGua^1, self.shiaGua)
            return(shangGua, shiaGua) 
        '''
        互卦
        '''
        def huGua(self):
            assert self.shangGua[0,0] != -1
            print("[classical互卦]")
            shangGua = np.array([ [self.shangGua[1,0]],
                                  [self.shangGua[2,0]],
                                  [self.shiaGua[0,0]]])
            shiaGua = np.array([ [self.shangGua[2,0]],
                                 [self.shiaGua[0,0]],
                                 [self.shiaGua[2,0]]])
            return(shangGua, shiaGua)
        '''
        綜卦
        '''
        def tzungGua(self):
            assert self.shangGua[0,0] != -1
            print("[classical綜卦]")
            shangGua = np.flip(self.shangGua)
            shiaGua = np.flip(self.shiaGua)
            return(shangGua, shiaGua)
        '''
        正卦
        '''
        def zhenGua(self):
            print("[classical正卦]")
            self.getGua("shangGua")
            self.getGua("shiaGua")
            return(self.shangGua, self.shiaGua)
        def getGua(self,mode="shangGua"): #Two mode: shanGua or shiaGua
            qr = QuantumRegister(3)
            cr = ClassicalRegister(3)
            circuit = QuantumCircuit(qr, cr)
            circuit.h(qr)
            circuit.measure(qr, cr)
            %matplotlib inline 
            circuit.draw(output='mpl')
            backend = Aer.get_backend('qasm_simulator')
            job = execute(circuit, backend, shots=1)
            result = job.result().get_counts(circuit)
            for x,y in result.items():
                Gua = x
                #print(Gua)
            if(mode=="shangGua"):
                self.shangGua[0,0] = Gua[2]
                self.shangGua[1,0] = Gua[1]
                self.shangGua[2,0] = Gua[0]
                #print(self.shangGua)
            elif(mode=="shiaGua"):
                self.shiaGua[0,0] = Gua[2]
                self.shiaGua[1,0] = Gua[1]
                self.shiaGua[2,0] = Gua[0]
                #print(self.shiaGua)
            else:
                print("mode error")



In [2]:
class QuantumOperator:
        
        def __init__(self):
            self.shangGua = np.array([[-1],[-1],[-1]])
            self.shiaGua = np.array([[-1],[-1],[-1]])
            self.shangGua_zhen = np.array([[-1],[-1],[-1]])
            self.shiaGua_zhen = np.array([[-1],[-1],[-1]])
            self.crBuffer = []
        '''
        變卦
        '''
        def bianGua(self): #shangGua: 上卦 shiaGua:下卦
            print("[Quantum變卦]")
            circ = QuantumCircuit(6)
            for i in range(6):
                circ.h(i)
                circ.x(i)
        
            circ.measure_all()
    
            simulator = Aer.get_backend('qasm_simulator')
            job = execute(circ, simulator, shots=1)
            result = job.result().get_counts(circ)
            self.__resultToGua(result)
            return(self.shangGua, self.shiaGua)
        '''
        互卦
        '''
        def huGua(self):
            print("[Quantum互卦]")
            qr = QuantumRegister(6)
            cr = ClassicalRegister(8) # cr[6]: for qr[0] cr[7]: for qr[5]
            circ = QuantumCircuit(qr, cr)
            for i in range(6):
                circ.h(i)
    
            circ.measure(qr[1], cr[0])
            circ.measure(qr[2], cr[1])
            circ.measure(qr[3], cr[2])
            circ.measure(qr[2], cr[3])
            circ.measure(qr[3], cr[4])
            circ.measure(qr[4], cr[5])

            circ.measure(qr[0], cr[6])
            circ.measure(qr[1], cr[7])
            simulator = Aer.get_backend('qasm_simulator')
            job = execute(circ, simulator, shots=1)
            result = job.result().get_counts(circ)
            
            for x,y in result.items():
                Gua = x
            self.shangGua[0,0]=Gua[7]
            self.shangGua[1,0]=Gua[6]
            self.shangGua[2,0]=Gua[5]
            self.shiaGua[2,0]=Gua[4]
            self.shiaGua[1,0]=Gua[3]
            self.shiaGua[0,0]=Gua[2]

            self.crBuffer.append(Gua[1])# q[0]
            self.crBuffer.append(Gua[0])# q[6]

            return(self.shangGua, self.shiaGua)
        '''
        綜卦
        '''
        def tzungGua(self):
            print("[Quantum綜卦]")
            circ = QuantumCircuit(6)
            for i in range(6):
                circ.h(i)
            circ.swap(0,2)
            circ.swap(3,5)
       
            circ.measure_all()
    
            simulator = Aer.get_backend('qasm_simulator')
            job = execute(circ, simulator, shots=1)
            result = job.result().get_counts(circ)
            self.__resultToGua(result)
            return(self.shangGua, self.shiaGua)
        '''
        正卦
        '''
        def zhenGua(self):
            print("[Quantum正卦]")
            circ = QuantumCircuit(6) # 6 qubits
            for i in range(6):
                circ.h(i)
            circ.measure_all()
            simulator = Aer.get_backend('qasm_simulator')
            job = execute(circ, simulator, shots=1)
            result = job.result().get_counts(circ)
            self.__resultToGua(result)
            return(self.shangGua, self.shiaGua)
        def __resultToGua(self, result): #string to shanGua & shiaGua
            for x,y in result.items():
                Gua = x
            self.shangGua[0,0]=Gua[5]
            self.shangGua[1,0]=Gua[4]
            self.shangGua[2,0]=Gua[3]
            self.shiaGua[2,0]=Gua[2]
            self.shiaGua[1,0]=Gua[1]
            self.shiaGua[0,0]=Gua[0]
        def transZhenGua(self, mode="huGua"): # mode = "huGua" or "bianGua" or "tzungGua" 
            if(mode=="huGua"):
                self.shangGua_zhen[0,0] = self.crBuffer[0]
                self.shangGua_zhen[1,0] = self.shangGua[0,0]
                self.shangGua_zhen[2,0] = self.shangGua[1,0]

                self.shiaGua_zhen[0,0] = self.shiaGua[1,0]
                self.shiaGua_zhen[1,0] = self.shiaGua[2,0]
                self.shiaGua_zhen[2,0] = self.crBuffer[1]

                return(self.shangGua_zhen, self.shiaGua_zhen)
            elif(mode=="bianGua"):
                self.shangGua_zhen = np.where((self.shangGua==0)|(self.shangGua==1), self.shangGua^1, self.shangGua)
                self.shiaGua_zhen = np.where((self.shiaGua==0)|(self.shiaGua==1), self.shiaGua^1, self.shiaGua)
                return(self.shangGua_zhen, self.shiaGua_zhen)
            elif(mode=="tzungGua"):
                self.shangGua_zhen = np.flip(self.shangGua)
                self.shiaGua_zhen = np.flip(self.shiaGua)
                return(self.shangGua_zhen, self.shiaGua_zhen)
            else:
                return -1 #error

In [3]:
classicalOp = ClassicalOperator()
classicalOp.zhenGua()
classicalOp.bianGua()
classicalOp.huGua()
classicalOp.tzungGua()

[classical正卦]
[classical變卦]
[classical互卦]
[classical綜卦]


(array([[0],
        [0],
        [1]]),
 array([[0],
        [1],
        [0]]))

In [4]:
quantumOp = QuantumOperator()
quantumOp.bianGua()
quantumOp.huGua()
quantumOp.tzungGua()
quantumOp.transZhenGua("tzungGua")

[Quantum變卦]
[Quantum互卦]
[Quantum綜卦]


(array([[1],
        [1],
        [0]]),
 array([[1],
        [1],
        [0]]))

In [5]:
def get64txt():
    zdic = {}
    with open('D:/QiskitHackathon/Divination/64.txt', encoding = 'utf8') as zfile:
        for line in zfile:
            z = line.split(' ', 1)
            key = z[0]
            value = z[1].split('，',1)
            zdic[key] = value
    return zdic
print(get64txt().get("111111"))
# for x,y in zdic.items():
#     print('%s %s %s' %(x,y[0],y[1])) 
zdic = get64txt()

['乾', '周易六十四卦之首。上下皆由相同的乾卦組成，其六個爻皆為陽。通稱「乾為天」。 代表「天」的形象。置於六十四卦之首、其次是象徵「地」的坤卦，序卦傳：天地定位、萬物生焉。\n']


In [6]:
def explanGua(shangGua, shiaGua):
    key = str(shangGua[0,0])+str(shangGua[1,0])+str(shangGua[2,0])+str(shiaGua[0,0])+str(shiaGua[1,0])+str(shiaGua[2,0])
    #print(key)
    #print(type(key))
    #print(zdic.get(key))
    return(zdic.get(key))


In [7]:
explanGua(quantumOp.shangGua_zhen, quantumOp.shiaGua_zhen)

['巽', '周易六十四卦中第五十七卦。上下卦皆由八卦中代表『風』的巽所組成，因此通稱為「巽為風」。序卦傳云：巽者，入也。象徵風「無孔不入」的特性。\n']

In [ ]:
print("Do you want to seek for prophecy?")
print("Let's Bu Gua!")
print("Please select the initial state.(1~2)")
print("[1] Hadamard Gate Type")
print("[2] U3 Gate ")
H3orU3 = int(input())
print(H3orU3)
if(H3orU3==1):
    print("Equip Hadamard Gate")
elif(H3orU3==2):
    print("Equip U3 Gate")
else:
    print("Select Again!")
print("Please decide how to Bu Gua .(1~2)")
print("[1] Just Measure")
print("[2] Stay Quantum")
HowTOBuGua = int(input())
print(HowTOBuGua)
if(HowTOBuGua==1):
    print("Just Measure")
elif(HowTOBuGua==2):
    print("Stay Quatum")
else:
    print("Select Again!")
if(H3orU3==1 and HowTOBuGua==1):# H3 and Just Measure
    COP = ClassicalOperator()
    print("Please decide how to Bu Gua.(1~4)")
    print("[1] Zhen Gua")
    print("[2] Bian Gua")
    print("[3] Hu Gua")
    print("[4] Tzung Gua")
    x = int(input())
    if(x==1): # 正卦
        print("[-----Prophecy-----]")
        COP.zhenGua()
        ExplanGua = explanGua(COP.shangGua, COP.shiaGua)
        
        print("[Zhen Gua]: ", ExplanGua[0])
        print("Oracle: ", ExplanGua[1])
    elif(x==2): # 變卦
        print("[-----Prophecy-----]")
        COP.zhenGua()
        ExplanGua = explanGua(COP.shangGua, COP.shiaGua)
        
        print("[Zhen Gua]: ", ExplanGua[0])
        print("Oracle: ", ExplanGua[1])
        Gua1, Gua2 = COP.bianGua()
        ExplanGua = explanGua(Gua1, Gua2)
        print("[Bian Gua]: ", ExplanGua[0])
        print("Oracle: ", ExplanGua[1])
    elif(x==3): #互卦
        print("[-----Prophecy-----]")
        COP.zhenGua()
        ExplanGua = explanGua(COP.shangGua, COP.shiaGua)
        
        print("[Zhen Gua]: ", ExplanGua[0])
        print("Oracle: ", ExplanGua[1])
        Gua1, Gua2 = COP.huGua()
        ExplanGua = explanGua(Gua1, Gua2)
        print("[Hu Gua]: ", ExplanGua[0])
        print("Oracle: ", ExplanGua[1])
    elif(x==4): # 綜卦
        print("[-----Prophecy-----]")
        COP.zhenGua()
        ExplanGua = explanGua(COP.shangGua, COP.shiaGua)
        
        print("[Zhen Gua]: ", ExplanGua[0])
        print("Oracle: ", ExplanGua[1])
        Gua1, Gua2 = COP.tzungGua()
        ExplanGua = explanGua(Gua1, Gua2)
        print("[Tzung Gua]: ", ExplanGua[0])
        print("Oracle: ", ExplanGua[1])
    else:
        print("Select Again")
elif(H3orU3==1 and HowTOBuGua==2):
    QOP = QuantumOperator()
    print("Please decide how to Bu Gua.(1~4)")
    print("[1] Zhen Gua")
    print("[2] Bian Gua")
    print("[3] Hu Gua")
    print("[4] Tzung Gua")
    x = int(input())
    if(x==1): # 正卦
        print("[-----Prophecy-----]")
        QOP.zhenGua()
        ExplanGua = explanGua(QOP.shangGua, QOP.shiaGua)
        
        print("[Zhen Gua]: ", ExplanGua[0])
        print("Oracle: ", ExplanGua[1])
    elif(x==2): # 變卦
        print("[-----Prophecy-----]")
        QOP.bianGua()
        ExplanGua = explanGua(COP.shangGua, COP.shiaGua)
        print("[Bian Gua]: ", ExplanGua[0])
        print("Oracle: ", ExplanGua[1])

        QOP.transZhenGua("bianGua")
        ExplanGua = explanGua(QOP.shangGua_zhen, QOP.shiaGua_zhen)
        print("[Zhen Gua]: ", ExplanGua[0])
        print("Oracle: ", ExplanGua[1])
        
    elif(x==3): #互卦
        print("[-----Prophecy-----]")
        QOP.huGua()
        ExplanGua = explanGua(QOP.shangGua, QOP.shiaGua)
        
        print("[Hu Gua]: ", ExplanGua[0])
        print("Oracle: ", ExplanGua[1])

        QOP.transZhenGua("huGua")
        ExplanGua = explanGua(QOP.shangGua_zhen, QOP.shiaGua_zhen)
        print("[Zhen Gua]: ", ExplanGua[0])
        print("Oracle: ", ExplanGua[1])
    elif(x==4): # 綜卦
        print("[-----Prophecy-----]")
        QOP.tzungGua()
        ExplanGua = explanGua(QOP.shangGua, QOP.shiaGua)
        print("[Tzung Gua]: ", ExplanGua[0])
        print("Oracle: ", ExplanGua[1])

        QOP.transZhenGua("tzungGua")
        ExplanGua = explanGua(QOP.shangGua_zhen, QOP.shiaGua_zhen)
        print("[Zhen Gua]: ", ExplanGua[0])
        print("Oracle: ", ExplanGua[1])
    else:
        print("Select Again")

Do you want to seek for prophecy?
Let's Bu Gua!
Please select the initial state.(1~2)
[1] Hadamard Gate Type
[2] U3 Gate 


In [1]:
print("hello")

hello


In [8]:
import numpy as np
class QuantumOperatorU3:
    def U3(self):
        circ = QuantumCircuit(7)
        for i in range(6):
            circ.h(i)
            circ.cx(i,6)

        circ.measure_all()

        simulator = Aer.get_backend('qasm_simulator')
        job = execute(circ, simulator, shots=1)
        result = job.result().get_counts(circ)
        b = result.items()
        for x, y in b:
            number = x
        number = str(number)

        def B(binary): 
            decimal = 0 
            for digit in binary: 
                decimal = decimal*2 + int(digit) 
            return decimal

        C = B(number)
        a = 1-(C/64)
        
        import numpy as np
        pi = np.pi
        b = np.arccos(a)
        return b
        
    def __init__(self):
        self.shangGua = np.array([[-1],[-1],[-1]])
        self.shiaGua = np.array([[-1],[-1],[-1]])
        self.shangGua_zhen = np.array([[-1],[-1],[-1]])
        self.shiaGua_zhen = np.array([[-1],[-1],[-1]])
        self.crBuffer = []
        '''
        變卦
        '''
    def bianGua(self): #shangGua: 上卦 shiaGua:下卦
        print("[Quantum變卦]")
        circ = QuantumCircuit(6)
        for i in range(6):
            circ.u3(self.U3(), 0, 0,[i])
            circ.x(i)
        
        circ.measure_all()
    
        simulator = Aer.get_backend('qasm_simulator')
        job = execute(circ, simulator, shots=1)
        result = job.result().get_counts(circ)
        self.__resultToGua(result)
        return(self.shangGua, self.shiaGua)
        '''
        互卦
        '''
    def huGua(self):
        print("[Quantum互卦]")
        qr = QuantumRegister(6)
        cr = ClassicalRegister(8) # cr[6]: for qr[0] cr[7]: for qr[5]
        circ = QuantumCircuit(qr, cr)
        for i in range(6):
            circ.u3(self.U3(), 0, 0,[i])
    
        circ.measure(qr[1], cr[0])
        circ.measure(qr[2], cr[1])
        circ.measure(qr[3], cr[2])
        circ.measure(qr[2], cr[3])
        circ.measure(qr[3], cr[4])
        circ.measure(qr[4], cr[5])

        circ.measure(qr[0], cr[6])
        circ.measure(qr[1], cr[7])
        simulator = Aer.get_backend('qasm_simulator')
        job = execute(circ, simulator, shots=1)
        result = job.result().get_counts(circ)
            
        for x,y in result.items():
            Gua = x
        self.shangGua[0,0]=Gua[7]
        self.shangGua[1,0]=Gua[6]
        self.shangGua[2,0]=Gua[5]
        self.shiaGua[2,0]=Gua[4]
        self.shiaGua[1,0]=Gua[3]
        self.shiaGua[0,0]=Gua[2]

        self.crBuffer.append(Gua[1])# q[0]
        self.crBuffer.append(Gua[0])# q[6]

        return(self.shangGua, self.shiaGua)
        '''
        綜卦
        '''
    def tzungGua(self):
        print("[Quantum綜卦]")
        circ = QuantumCircuit(6)
        for i in range(6):
            circ.u3(self.U3(), 0, 0,[i])
        circ.swap(0,2)
        circ.swap(3,5)
       
        circ.measure_all()
    
        simulator = Aer.get_backend('qasm_simulator')
        job = execute(circ, simulator, shots=1)
        result = job.result().get_counts(circ)
        self.__resultToGua(result)
        return(self.shangGua, self.shiaGua)
    def __resultToGua(self, result): #string to shanGua & shiaGua
            for x,y in result.items():
                Gua = x
            self.shangGua[0,0]=Gua[5]
            self.shangGua[1,0]=Gua[4]
            self.shangGua[2,0]=Gua[3]
            self.shiaGua[2,0]=Gua[2]
            self.shiaGua[1,0]=Gua[1]
            self.shiaGua[0,0]=Gua[0]
    def transZhenGua(self, mode="huGua"): # mode = "huGua" or "bianGua" or "tzungGua" 
            if(mode=="huGua"):
                self.shangGua_zhen[0,0] = self.crBuffer[0]
                self.shangGua_zhen[1,0] = self.shangGua[0,0]
                self.shangGua_zhen[2,0] = self.shangGua[1,0]

                self.shiaGua_zhen[0,0] = self.shiaGua[1,0]
                self.shiaGua_zhen[1,0] = self.shiaGua[2,0]
                self.shiaGua_zhen[2,0] = self.crBuffer[1]

                return(self.shangGua_zhen, self.shiaGua_zhen)
            elif(mode=="bianGua"):
                self.shangGua_zhen = np.where((self.shangGua==0)|(self.shangGua==1), self.shangGua^1, self.shangGua)
                self.shiaGua_zhen = np.where((self.shiaGua==0)|(self.shiaGua==1), self.shiaGua^1, self.shiaGua)
                return(self.shangGua_zhen, self.shiaGua_zhen)
            elif(mode=="tzungGua"):
                self.shangGua_zhen = np.flip(self.shangGua)
                self.shiaGua_zhen = np.flip(self.shiaGua)
                return(self.shangGua_zhen, self.shiaGua_zhen)
            else:
                return -1 #error

In [9]:
quantumOp = QuantumOperatorU3()
quantumOp.tzungGua()
quantumOp.bianGua()
quantumOp.huGua()
quantumOp.transZhenGua("tzungGua")

[Quantum綜卦]
[Quantum變卦]
[Quantum互卦]


(array([[1],
        [0],
        [0]]),
 array([[0],
        [1],
        [1]]))

In [26]:
import numpy as np
from qiskit import *
class ClassicalOperatorU3:
        
    def U3(self):
        circ = QuantumCircuit(7)
        for i in range(6):
            circ.h(i)
            circ.cx(i,6)

        circ.measure_all()

        simulator = Aer.get_backend('qasm_simulator')
        job = execute(circ, simulator, shots=1)
        result = job.result().get_counts(circ)
        b = result.items()
        for x, y in b:
            number = x
        number = str(number)

        def B(binary): 
            decimal = 0 
            for digit in binary: 
                decimal = decimal*2 + int(digit) 
            return decimal

        C = B(number)
        a = 1-(C/64)

    #circ1 = QuantumCircuit(6)
        import numpy as np
        pi = np.pi
        b = np.arccos(a)
        return b
        
    def __init__(self):
        self.shangGua = np.array([[-1],[-1],[-1]])
        self.shiaGua = np.array([[-1],[-1],[-1]])
    '''
    變卦
    '''
    def bianGua(self): #shangGua: 上卦 shiaGua:下卦
        assert self.shangGua[0,0] != -1
        print("[classical變卦]")
        shangGua = np.where((self.shangGua==0)|(self.shangGua==1), self.shangGua^1, self.shangGua)
        shiaGua = np.where((self.shiaGua==0)|(self.shiaGua==1), self.shiaGua^1, self.shiaGua)
        return(shangGua, shiaGua) 
    '''
    互卦
    '''
    def huGua(self):
        assert self.shangGua[0,0] != -1
        print("[classical互卦]")
        shangGua = np.array([ [self.shangGua[1,0]],
                              [self.shangGua[2,0]],
                              [self.shiaGua[0,0]]])
        shiaGua = np.array([ [self.shangGua[2,0]],
                             [self.shiaGua[0,0]],
                             [self.shiaGua[2,0]]])
        return(shangGua, shiaGua)
    '''
    綜卦
    '''
    def tzungGua(self):
        assert self.shangGua[0,0] != -1
        print("[classical綜卦]")
        shangGua = np.flip(self.shangGua)
        shiaGua = np.flip(self.shiaGua)
        return(shangGua, shiaGua)
    '''
    正卦
    '''
    def zhenGua(self):
        print("[classical正卦]")
        self.getGua("shangGua")
        self.getGua("shiaGua")
        return(self.shangGua, self.shiaGua)
    def getGua(self,mode="shangGua"): #Two mode: shanGua or shiaGua
        qr = QuantumRegister(3)
        cr = ClassicalRegister(3)
        circuit = QuantumCircuit(qr, cr)
        for i in range(3):
            circuit.u3(self.U3(), 0, 0,[i])
        circuit.measure(qr, cr)
        get_ipython().run_line_magic('matplotlib', 'inline')
        circuit.draw(output='mpl')
        backend = Aer.get_backend('qasm_simulator')
        job = execute(circuit, backend, shots=1)
        result = job.result().get_counts(circuit)
        for x,y in result.items():
            Gua = x
                #print(Gua)
        if(mode=="shangGua"):
            self.shangGua[0,0] = Gua[2]
            self.shangGua[1,0] = Gua[1]
            self.shangGua[2,0] = Gua[0]
                #print(self.shangGua)
        elif(mode=="shiaGua"):
            self.shiaGua[0,0] = Gua[2]
            self.shiaGua[1,0] = Gua[1]
            self.shiaGua[2,0] = Gua[0]
                #print(self.shiaGua)
        else:
            print("mode error")

In [27]:
classicalOpu3 = ClassicalOperatorU3()
classicalOpu3.zhenGua()
classicalOpu3.bianGua()
classicalOpu3.huGua()
classicalOpu3.tzungGua()

[classical正卦]
[classical變卦]
[classical互卦]
[classical綜卦]


(array([[0],
        [1],
        [0]]),
 array([[1],
        [1],
        [1]]))

In [19]:
print("hi")

hi
